### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by DaneelReventelov** [MgAl2O4/FFRadarBuddy#1]
Can you add  filter for monster, npc, PG, etc
In hunt train is not possibile to add the monster to the white list for the refresh speed
ty

**Comment by MgAl2O4** [comment]
Added auto updates for filter presets in v2 and a few basic ones:
- hunt only (all ranks)
- hunt only (A, S)
- players only
- npcs only

Let me know if there are other lists that can be useful, it's now quite easy to add more.

**Comment by DaneelReventelov** [comment]
Wonderful, really useful. If I'll see something other I'll let you know :)+
